spring.application.name=mango2j
spring.datasource.url=jdbc:h2:file:./db/cache
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=admin
spring.datasource.password=internal
spring.jpa.hibernate.ddl-auto=update
server.error.whitelabel.enabled=false
server.error.path=/error
mango.baseDir=./library
spring.servlet.multipart.max-file-size=2048MB
spring.servlet.multipart.max-request-size=2048MB
spring.autoconfigure.exclude=org.springframework.ai.model.transformers.autoconfigure.TransformersEmbeddingModelAutoConfiguration