name: Java CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout repository
      uses: actions/checkout@v4
    - name: setup jdk 21
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21
    - name: Build with Maven
      run: ./mvnw install
    - name: Upload Artifact
      uses: actions/upload-artifact@v2-preview
      with:
        name: Mango2j
        path: target/*.jar